"""Markdown + embedded-JSON report generator.

The output is one Markdown file at
``docs/RE_ACCEPTANCE_REPORT_<UTC-timestamp>.md`` with two consumers in mind:

  - A human reader (Architect) who scrolls and looks for FAIL / MANUAL
    blocks. They want to know "what do I do next?"
  - An AI agent (the next session) who reads the trailing JSON code block
    and pattern-matches on case IDs.

Sections (in order, Architect-first):
  1. Top-line status + TL;DR ("what do I do?")
  2. Patch log (if docsync made any drift corrections)
  3. Summary (counts + per-invariant table)
  4. FAIL section (architect must fix)
  5. AUTO results (by invariant) — each row's notes gives a
     how-to-make-it-PASS or how-to-fix-it
  6. MANUAL section — each entry expands to a code block with
     判据 / 怎么跑 / 记到哪 / 自动判定
  7. ENV_BLOCKED callout (architect need not act)
  8. JSON block for agent consumption
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT / "tools") not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT / "tools"))

from tools.acceptance.cases import (  # type: ignore[import-not-found]
    CaseSpec,
    ENV_BLOCKED,
    FAIL,
    MANUAL_FIXTURE_REQUIRED,
    PASS,
    SKIPPED,
    UNJUDGED,
)
from tools.acceptance.runner import (  # type: ignore[import-not-found]
    LONG_RUN_DONE,
    LONG_RUN_FAIL,
    LONG_RUN_SKIPPED,
    LONG_RUN_TIMEOUT,
    CaseResult,
)


def timestamp_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def summarize(results: Iterable[Tuple[CaseSpec, CaseResult]]) -> Dict[str, Any]:
    by_status: Counter = Counter()
    by_invariant: Dict[str, Counter] = {}
    by_kind: Counter = Counter()  # MIRRORED vs VERIFIED
    total = 0
    for case, result in results:
        by_status[result.status] += 1
        total += 1
        key = f"#{case.invariant}" if case.invariant is not None else "cross"
        by_invariant.setdefault(key, Counter())[result.status] += 1
        kind = result.payload.get("kind", "VERIFIED") if result.payload else "VERIFIED"
        by_kind[kind] += 1
    return {
        "total": total,
        "by_status": dict(by_status),
        "by_invariant": {k: dict(v) for k, v in by_invariant.items()},
        "by_kind": dict(by_kind),
    }


def _escape_cell(text: str) -> str:
    """Make text safe to drop in a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", "<br>")


def render_markdown(
    cases_results: List[Tuple[CaseSpec, CaseResult]],
    *,
    docs_changes: List[str] | None = None,
    repo_root: Path | None = None,
) -> str:
    del repo_root  # reserved for future per-repo customisation
    summary = summarize(cases_results)
    ts = timestamp_utc()
    bs = summary["by_status"]
    n_fail = bs.get(FAIL, 0)
    n_manual = bs.get(MANUAL_FIXTURE_REQUIRED, 0)
    n_unjudged = bs.get(UNJUDGED, 0)
    n_blocked = bs.get(ENV_BLOCKED, 0)
    n_pass = bs.get(PASS, 0)
    n_long_done = bs.get(LONG_RUN_DONE, 0)
    n_long_timeout = bs.get(LONG_RUN_TIMEOUT, 0)
    n_long_fail = bs.get(LONG_RUN_FAIL, 0)
    n_long_skip = bs.get(LONG_RUN_SKIPPED, 0)

    lines: List[str] = []
    lines.append(f"# RE Acceptance Report — {ts}")
    lines.append("")
    lines.append(
        "Generated by `tools/run_acceptance.py run`. Each row corresponds "
        "to a `CaseSpec` in `tools/acceptance/cases.py` and to a section in "
        "`docs/RE_ACCEPTANCE_CASES.md`."
    )
    lines.append("")

    # ---- docsync patch log ----
    if docs_changes:
        lines.append("## 修订记录")
        lines.append("")
        lines.append(
            "Docsync found drift between the guide and the live repo; the "
            "following changes were applied to `docs/RE_ACCEPTANCE_CASES.md` "
            "before this report was finalised:"
        )
        lines.append("")
        for change in docs_changes:
            lines.append(f"- {change}")
        lines.append("")

    # ---- TL;DR: what should the Architect do? ----
    lines.append("## TL;DR — Architect 接下来该做什么")
    lines.append("")
    if n_fail:
        lines.append(
            f"🔴 **FAIL = {n_fail}**: 工具自身有断言失败。先看下面 '## 需架构师处理的 FAIL' 段,"
            f"修 runner 或 fixture 后再 `make acceptance`。"
        )
        lines.append("")
    if n_manual:
        lines.append(
            f"🟡 **MANUAL = {n_manual}**: 必须你亲手跑 (演练 D1/D2/D3 / `--bare` / 跨客户端)。"
        )
        lines.append(
            "  → 看下面 '## 需架构师亲手跑的 case' 段,每条按 **判据 / 怎么跑 / 记到哪 / 自动判定** 走。"
        )
        lines.append("")
    if n_unjudged:
        lines.append(
            f"⚪ **UNJUDGED = {n_unjudged}**: 真验证过了,但当前父仓库 idle,数据不足以判定 "
            "(不是 invariant 失败,等 research 轨道恢复后再跑一次即可)。\n"
            f"   详情看下面每个 UNJUDGED case 的 '备注' 列——里面写了'怎么变 PASS'。"
        )
        lines.append("")
    if n_blocked:
        lines.append(
            f"⏸  **ENV_BLOCKED = {n_blocked}**: 端点/环境策略阻断,已被 architect 决策复述——"
            f"**不在 B 类清单**。详见 '## ENV_BLOCKED 段'。"
        )
        lines.append("")
    if n_long_done or n_long_timeout or n_long_fail or n_long_skip:
        lines.append(
            f"🔬 **LONG_RUN**: done={n_long_done}, timeout={n_long_timeout}, "
            f"fail={n_long_fail}, skipped={n_long_skip}"
        )
        if n_long_skip:
            lines.append(
                "  skipped 是因为 pre-flight 检测到 claude 端点不可用——"
                "**不是 case 失败**,是工具链路状态。"
            )
        lines.append("")
    if not (n_fail or n_manual or n_unjudged or n_blocked):
        lines.append(
            "✅ **全 PASS**。本仓库 RE 验收已闭环。下次有 V0/V1 状态表变动或 invariant 修订时再跑。"
        )
        lines.append("")
    # by_kind breakdown — separates MIRRORED (status-table reread) from
    # VERIFIED (real probes). This is the architectural signal that lets
    # the reader tell which PASSes were independently confirmed today.
    by_kind = summary.get("by_kind", {})
    n_mirrored = by_kind.get("MIRRORED", 0)
    n_verified = by_kind.get("VERIFIED", 0)
    if n_mirrored or n_verified:
        lines.append(
            f"📋 **By kind**: MIRRORED={n_mirrored} (复用 V0/V1_ACCEPTANCE_GUIDE.md 状态表 — "
            f"无新证据), VERIFIED={n_verified} (本次真实探测)"
        )
        if n_mirrored:
            lines.append(
                "   MIRRORED case 不是本次新验证——读的是状态表里的旧 verdict。"
                "如果 architect 想确认这些 case 仍成立,把它们改成真实验证。"
            )
        lines.append("")

    # ---- summary ----
    lines.append("## 摘要")
    lines.append("")
    lines.append(f"- **总 case**: {summary['total']}")
    lines.append(f"- **PASS**: {n_pass}")
    lines.append(f"- **FAIL**: {n_fail}")
    lines.append(f"- **ENV_BLOCKED**: {n_blocked}")
    lines.append(f"- **MANUAL_FIXTURE_REQUIRED**: {n_manual}")
    lines.append(f"- **UNJUDGED**: {n_unjudged}")
    lines.append(f"- **SKIPPED**: {bs.get(SKIPPED, 0)}")
    lines.append("")
    lines.append("按 invariant 分组：")
    lines.append("")
    lines.append("| invariant | PASS | FAIL | ENV | MANUAL | UNJUDGED | SKIPPED |")
    lines.append("|---|---|---|---|---|---|---|")
    for key in sorted(summary["by_invariant"].keys(),
                      key=lambda k: (k == "cross", k)):
        c = summary["by_invariant"][key]
        lines.append(
            f"| {key} | {c.get(PASS, 0)} | {c.get(FAIL, 0)} | "
            f"{c.get(ENV_BLOCKED, 0)} | {c.get(MANUAL_FIXTURE_REQUIRED, 0)} | "
            f"{c.get(UNJUDGED, 0)} | {c.get(SKIPPED, 0)} |"
        )
    lines.append("")

    # ---- FAIL section ----
    failures = [(c, r) for c, r in cases_results if r.status == FAIL]
    lines.append("## 需架构师处理的 FAIL")
    lines.append("")
    if failures:
        lines.append("| case-id | 标题 | 错在哪 | 怎么修 |")
        lines.append("|---|---|---|---|")
        for case, result in failures:
            err = _escape_cell(result.error or "")[:120]
            note = _escape_cell(result.notes or "")[:240]
            lines.append(
                f"| `{case.id}` | {case.title} | `{err}` | {note} |"
            )
        lines.append("")
    else:
        lines.append("_无 FAIL — 工具自身链路健康。_\n")

    # ---- AUTO results (by invariant) ----
    lines.append("## 自动跑结果（按 invariant 分组）")
    lines.append("")
    lines.append(
        "**怎么读**: PASS = 已建立的事实状态;UNJUDGED = 父仓库数据不够,但 invariant "
        "本身已被状态表认证,无需操作;ENV_BLOCKED = 环境不允许,architect 决策已复述。"
        "每个 case 的 **备注** 列直接给'怎么变 PASS / 怎么修 / 该记到哪'。"
    )
    lines.append("")
    grouped: Dict[str, List[Tuple[CaseSpec, CaseResult]]] = {}
    for case, result in cases_results:
        if result.status == MANUAL_FIXTURE_REQUIRED:
            continue
        key = f"#{case.invariant}" if case.invariant is not None else "cross"
        grouped.setdefault(key, []).append((case, result))
    for key in sorted(grouped.keys(), key=lambda k: (k == "cross", k)):
        lines.append(f"### 不变量 {key}")
        lines.append("")
        lines.append("| case-id | 标题 | exit | 状态 | 耗时 | 备注(给架构师) |")
        lines.append("|---|---|---|---|---|---|")
        for case, result in grouped[key]:
            note = _escape_cell(result.notes or "")[:400]
            dur = f"{result.duration_s:.2f}s"
            lines.append(
                f"| `{case.id}` | {case.title} | {result.exit_code} | "
                f"**{result.status}** | {dur} | {note} |"
            )
        lines.append("")

    # ---- MANUAL section with judgement criteria ----
    manual = [(c, r) for c, r in cases_results if r.status == MANUAL_FIXTURE_REQUIRED]
    if manual:
        lines.append("## 需架构师亲手跑的 case")
        lines.append("")
        lines.append(
            "每条给四件事:\n"
            "- **判据** —— 这次跑看什么算 PASS\n"
            "- **怎么跑** —— 命令 + 给 session 的 prompt(D1/D3 不能补任何提示)\n"
            "- **记到哪** —— 跑完把结果粘到哪个文档\n"
            "- **自动判定** —— 是否能用 `tests/main/` 脚本自动判"
        )
        lines.append("")
        for case, result in manual:
            lines.append(f"### `{case.id}` — {case.title}")
            lines.append("")
            lines.append("```")
            lines.append(result.notes or "(no notes)")
            lines.append("```")
            lines.append("")

    # ---- ENV_BLOCKED callout ----
    blocked = [(c, r) for c, r in cases_results if r.status == ENV_BLOCKED]
    if blocked:
        lines.append("## ENV_BLOCKED 段")
        lines.append("")
        lines.append(
            "环境或端点策略阻断,已被 architect 决策复述。**不在 B 类清单**——架构师无需操作。"
        )
        lines.append("")
        for case, result in blocked:
            note = _escape_cell(result.notes or "")[:300]
            lines.append(f"- **`{case.id}`** ({case.title}): {note}")
        lines.append("")

    # ---- footer ----
    lines.append("---")
    lines.append("")
    lines.append(
        f"Run took {sum(r.duration_s for _, r in cases_results):.2f}s "
        f"across {summary['total']} cases. Generated by "
        f"`tools/run_acceptance.py` at {ts}."
    )
    return "\n".join(lines) + "\n"


def render_json_block(cases_results: List[Tuple[CaseSpec, CaseResult]]) -> str:
    payload = {
        "generated_at": timestamp_utc(),
        "summary": summarize(cases_results),
        "cases": [
            {
                "id": case.id,
                "title": case.title,
                "invariant": case.invariant,
                "level": case.level,
                "expected": case.expected,
                "source": case.source,
                **result.to_dict(),
            }
            for case, result in cases_results
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


def write_report(
    out_path: Path,
    cases_results: List[Tuple[CaseSpec, CaseResult]],
    docs_changes: List[str] | None = None,
) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = render_markdown(
        cases_results,
        docs_changes=docs_changes or [],
        repo_root=out_path.parent.parent,
    )
    json_block = render_json_block(cases_results)
    out_path.write_text(
        body + "\n```json\n" + json_block + "\n```\n",
        encoding="utf-8",
    )
    return out_path
