'use strict';
const $ = id => document.getElementById(id);
const labels = {idle:'记录为空闲',planning_evidence:'准备研究',running:'记录为运行中',active:'当前焦点',queued:'待探索',parked:'暂存',blocked:'受阻',completed:'已完成',rejected:'已否定',confirmed:'局部支持',inconclusive:'尚无定论',informative_failure:'暴露有效问题',failed:'运行失败',none:'检查记录',Open:'开放判断',Established:'已建立的局部事实',Provisional:'暂定判断',Supported:'获得支持',Superseded:'已被替代',Refuted:'已反驳'};
let snapshot;
const label = x => labels[x] || x || '未记录';
const date = x => x ? new Date(x).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}) : '时间未记录';
const text = x => typeof x === 'string' ? x : x == null ? '未记录' : JSON.stringify(x,null,2);
function el(tag, cls, value) {const n=document.createElement(tag);if(cls)n.className=cls;if(value!=null)n.textContent=text(value);return n;}
function pill(value){return el('span','pill '+String(value).replace(/[^a-zA-Z_]/g,''),label(value));}
function section(title,value){const box=el('section');box.append(el('h3',null,title),el('p',null,value));return box;}
function openDetail(title,nodes){$('detail-title').textContent=title;$('detail-body').replaceChildren(...nodes);if(!$('detail').open)$('detail').show();document.body.classList.add('detail-open');}
function rawDetail(value){const box=el('details');box.append(el('summary',null,'原始记录（含来源与适用边界）'),el('pre',null,JSON.stringify(value,null,2)));return box;}
function inspectRef(id){const p=snapshot.payload;const f=p.conclusions.find(x=>x.id===id);if(f)return findingDetail(f);const r=p.routes.find(x=>x.id===id);if(r)return routeDetail(r);const e=snapshot.events.find(x=>x.id===id);if(e)return eventDetail(e);openDetail('摘要引用的来源',[section('来源',id),section('说明','此来源未包含在轻量快照中，请在研究会话中按该路径或 ID 检视。摘要的来源指纹覆盖 canonical 状态与已登记证据，但不证明原始产物仍有效。')]);}
function refs(items){const box=el('div');for(const id of items||[]){const b=el('button','ref',id+' ↗');b.onclick=()=>inspectRef(id);box.append(b);}return box;}
function translated(group,id){return snapshot.translations?.[group]?.[id] || null;}
function chinese(value, fallback){return typeof value==='string' && /[\u3400-\u9fff]/.test(value) ? value : fallback;}
function routeDetail(r){const translatedRow=translated('routes',r.id);openDetail(translatedRow?.text||r.title,[pill(r.status),...(translatedRow?[section('应用意义',translatedRow.detail||translatedRow.text)]:[]),section('研究问题',r.question),section('保留 / 排序理由',r.reason),section('下一项验证',r.next_probe),section('恢复条件',r.wake_when||'无额外条件登记；执行仍以会话授权为准。'),section('依赖路线',r.depends_on?.length?r.depends_on.join('\n'):'未登记依赖'),section('替代路线',r.alternatives?.length?r.alternatives.join('\n'):'未登记替代关系'),refs(r.evidence),rawDetail(r)]);}
function findingDetail(f){const t=translated('conclusions',f.id);const nodes=[pill(f.status),...(t?[section('当前理解',t.text)]:[]),section('对应用 / 架构的影响',f.implication),section('未证明什么',f.limitation),refs(f.evidence)];if(f.superseded_by)nodes.push(section('修正原因',f.reason),refs([f.superseded_by]));for(const [i,r] of (f.reports||[]).entries()){const b=el('button',null,'阅读研究报告 ↗ '+r.path);b.onclick=async()=>{b.disabled=true;try{const response=await fetch('/api/report?finding='+encodeURIComponent(f.id)+'&index='+i);const data=await response.json();if(!response.ok)throw Error(data.error);openDetail('研究报告',[section('来源与完整性',data.path+' · '+({match:'与登记指纹一致',changed:'警告：内容已变更，不能作为原记录的相同产物',unrecorded:'未登记内容指纹'}[data.integrity])),el('pre',null,data.text)]);}catch(e){openDetail('报告无法读取',[section('原因',e.message)]);}finally{b.disabled=false;}};nodes.push(b);}if(!f.reports?.length)nodes.push(section('研究文档','尚未关联独立研究报告；以下原始记录不是完整研究报告。'));nodes.push(rawDetail(f));openDetail(t?.text||chinese(f.title,'研究结论 '+f.id),nodes);}
function eventDetail(e){const t=translated('events',e.id);openDetail(t?.text||chinese(e.title,'新研究记录 '+e.id),[pill(e.outcome),section('记录时间',date(e.at)),...(t?[section('意义',t.detail||t.text)]:[]),section('实际记录',Array.isArray(e.detail)?e.detail.join('\n\n'):e.detail),rawDetail(e)]);}
function render(data){snapshot=data;const p=data.payload;const brief=['current','stale'].includes(data.brief_status)?data.brief:null;const fresh=data.brief_status==='current';$('project').textContent=data.project;$('status').textContent=label(p.recorded_status);$('updated').textContent='状态记录于 '+date(p.updated_at);$('brief-date').textContent=brief?'摘要生成于 '+date(brief.generated_at):'尚未发布中文摘要';$('freshness').textContent=fresh?'中文摘要与当前持久记录一致 · 每 5 秒读取一次 · 不代表进程存活或结论已验证':data.brief_status==='stale'?'研究记录已变化；下方保留上次中文判断（待更新），最新路线状态见研究路线。':data.brief_status==='invalid'?'中文摘要格式无效，已隐藏；研究原始记录仍可查看。':'尚无中文架构摘要。下方可查看原始记录；在研究会话发布摘要后，首屏将显示应用判断。';$('freshness').classList.toggle('warning',!fresh);document.querySelector('.brief').classList.toggle('stale',!fresh);
 $('brief-panel').hidden=!brief;$('brief-label').textContent=fresh?'当前判断':'上次中文判断 · 待更新';
 $('activity-text').textContent=data.activity?.text|| (p.block?chinese(p.block.objective,'本轮目标的中文说明待更新；可展开查看实际持久记录。'):'尚未记录研究块');$('activity-meta').textContent=p.block?String(p.block.id)+' · 开始记录于 '+date(p.block.started_at)+' · '+label(p.recorded_status):'无研究块记录';
 for(const key of ['headline','goal','capability','gap','next','decision']){const target=$(key);target.replaceChildren();if(brief){target.append(document.createTextNode(brief[key].text));if(key!=='headline'&&key!=='goal')target.append(refs(brief[key].refs));}else target.textContent='';}
 $('routes').replaceChildren();const sorted=[...p.routes].sort((a,b)=>(a.status==='active'?-1:1)-(b.status==='active'?-1:1)||a.priority-b.priority);$('route-count').textContent=sorted.length+' 条保留路线';for(const r of sorted){const t=translated('routes',r.id);const b=el('button','route'+(r.status==='active'?' focus':''));const top=el('div','route-top');top.append(el('h3',null,t?.text||chinese(r.title,'研究路线 '+r.id)),pill(r.status));b.append(top,el('p',null,t?.detail||chinese(r.reason,'该路线的中文说明待更新；点击查看原始依据。')));const meta=el('div','route-meta');meta.append(el('span',null,'建议优先级 '+r.priority),el('span',null,'依据与恢复条件 ↗'));b.append(meta);b.onclick=()=>routeDetail(r);$('routes').append(b);}if(!sorted.length)$('routes').append(el('p','empty','尚未登记路线；不代表没有其他值得研究的方向。'));
 $('events').replaceChildren();for(const e of data.events.slice(0,10)){const t=translated('events',e.id);const b=el('button','event'+(e.kind==='route'?' route-event':''));const meta=el('div','meta');meta.append(el('span',null,date(e.at)),el('span',null,e.kind==='route'?'路线 → '+label(e.outcome):label(e.outcome)));b.append(meta,el('p',null,t?.text||chinese(e.title,'新研究记录 '+e.id)));b.onclick=()=>eventDetail(e);$('events').append(b);}if(!data.events.length)$('events').append(el('p','empty','尚无已落地的证据或路线变更。'));
 $('conclusions').replaceChildren();const fs=[...p.conclusions].sort((a,b)=>(a.status==='Superseded'?1:0)-(b.status==='Superseded'?1:0)||String(b.updated_at||b.created_at).localeCompare(String(a.updated_at||a.created_at)));const reports=fs.reduce((n,f)=>n+(f.reports||[]).length,0);$('finding-count').textContent=fs.length+' 条判断 · '+reports+' 份关联文档';for(const f of fs){const t=translated('conclusions',f.id);const b=el('button','conclusion'+(f.status==='Superseded'?' superseded':''));b.append(pill(f.status),el('h3',null,t?.text||chinese(f.title,'研究结论 '+f.id)),el('span','meta',(f.reports?.length?'研究文档 '+f.reports.length+' 份 · ':'')+'查看依据与局限 ↗'));b.onclick=()=>findingDetail(f);$('conclusions').append(b);}if(!fs.length)$('conclusions').append(el('p','empty','尚无持久结论；未把实验数量当作成果。'));
 $('health').textContent=data.findings?.length?'记录检查发现 '+data.findings.length+' 项问题':'记录检查未发现结构问题（不验证科学结论）';
}
let loading=false;
async function refresh(){if(loading)return;loading=true;$('refresh').disabled=true;try{const response=await fetch('/api/snapshot');const data=await response.json();if(!response.ok)throw Error(data.error);render(data);$('error').hidden=true;}catch(e){$('error').textContent=e.message+' · 当前画面可能已过期。';$('error').hidden=false;}finally{loading=false;$('refresh').disabled=false;}}
$('activity-details').onclick=()=>{if(!snapshot)return;const p=snapshot.payload;openDetail('本轮研究的实际记录',[section('说明','此处是实时读取的持久记录，不是模型实时监控；原始字段保留英文。'),rawDetail({block:p.block,current_observation:p.current_observation,next_action:p.next_action,recorded_status:p.recorded_status,updated_at:p.updated_at})]);};
$('refresh').onclick=refresh;$('close').onclick=()=>$('detail').close();$('diagnostics').onclick=()=>{if(!snapshot)return;openDetail('记录与校验依据',[section('数据范围','持久研究状态、路线切换和最近证据。没有模型进程心跳，页面每次刷新不代表 AI 有新进展。'),section('摘要来源指纹',snapshot.source_revision),section('摘要新鲜度范围','指纹覆盖 TASK 与 canonical 记录，不核查整个应用工作树及所有外部数据。原始报告打开时另查内容指纹。'),el('pre',null,JSON.stringify({findings:snapshot.findings,recorded_status:snapshot.payload.recorded_status,current_observation:snapshot.payload.current_observation,next_action:snapshot.payload.next_action,git_dirty:snapshot.payload.git_dirty,block:snapshot.payload.block},null,2))]);};
$('detail').addEventListener('close',()=>document.body.classList.remove('detail-open'));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&$('detail').open)$('detail').close();});
refresh();setInterval(()=>{if(!document.hidden&&!$('detail').open)refresh();},5000);
